import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/feature/app-sidebar";
import { AppSessionProvider } from "@/context/app-session-context";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <AppSessionProvider>
            <SidebarProvider defaultOpen={true}>
              <AppSidebar />
              <main className="min-h-screen w-full">
                {children}
              </main>
            </SidebarProvider>
          </AppSessionProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
